version: '3'
services:
    store:
        build: .
        ports:
            - "9090:9090"
        environment:
            - STORE_ENV=docker
    ipfs:
        image: jbenet/go-ipfs:latest
        volumes:
            - /tmp/ipfs/:/data/ipfs/
        ports:
            - "8080:8080"
            - "4001:4001"
            - "5001:5001"
        command: 'daemon --enable-pubsub-experiment'
