version: '3'
services:
    store-seed:
        shm_size: 500M
        build: .
        ports:
            - "9090:9090"
        environment:
            STORE_ENV: docker
            PUBLISH_HOST: store-seed
            PUBLISH_PORT: 2551
            SEED_NODE: akka://consensus-system@store-seed:2551
        networks:
            - akka-cluster
    ipfs:
        image: jbenet/go-ipfs:latest
        networks:
            - akka-cluster

networks:
    akka-cluster:
