version: '3'
services:
    ipfs-cluster:
        image: jbenet/go-ipfs:latest
    store-cluster:
        shm_size: 500M
        build: .
        depends_on:
            - ipfs-cluster
        ports:
            - "9091-9200:9090"
        environment:
            STORE_ENV: docker
            PRIMARY: "false"
            FAULT_THRESHOLD: 0
            SEED_NODE: akka://consensus-system@store-seed:2551
            WAIT_HOSTS:
                ipfs-cluster:5001
networks:
    default:
        external:
            name: mongochain_akka-cluster
