version: '3'
services:
    ipfs:
        image: jbenet/go-ipfs:latest
    community-assignment-server:
        build:
            context: ./community-assigment-server/
        ports:
            - "5000:5000"
    store:
        shm_size: 500M
        build: .
        depends_on:
            - ipfs
            - community-assignment-server
        ports:
            - "9090-10000:9090"
        environment:
            WAIT_HOSTS:
                ipfs:5001, community-assignment-server:5000
