package cluster.logging;

public enum EventType {
    CLIENT_NEW_TRANSACTION,
    PRIMARY_NEW_PREPREPARE,
    REPLICA_NEW_PREPARE,
    REPLICA_RECEIVE_PREPARE,
    REPLICA_NEW_COMMIT,
    REPLICA_RECEIVE_COMMIT,
    REPLICA_NEW_RESULT,
    REPLICA_CONSENSUS_RESULT,
    REPLICA_BROADCAST_RESULT,
    PRIMARY_RECEIVE_LOCAL_RESULT,
    PRIMARY_BROADCAST_TO_FINAL,
    PRIMARY_BROADCAST_GLOBAL_RESULT,
    CLIENT_INTEGRATE_GLOBAL_RESULT,
}
