package cluster.logging;

public enum EventType {
    CLIENT_NEW_TRANSACTION,
    PRIMARY_NEW_PREPREPARE,
    REPLICA_NEW_PREPARE,
    REPLICA_RECEIVE_PREPARE,
    REPLICA_NEW_COMMIT,
    REPLICA_RECEIVE_COMMIT,
    REPLICA_NEW_RESULT,
    REPLICA_CONSENSUS_RESULT,
    REPLICA_INTEGRATE_RESULT,
    CLIENT_CONSENSUS_RESULT,
    CLIENT_INTEGRATE_RESULT,
}
